In [7]:
pip install yfinance

Requirement already satisfied: yfinance in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (1.5.1)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: requests>=2.31 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (2.33.1)
Requirement already satisfied: multitasking>=0.0.7 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (2026.2)
Requirement already satisfied: peewee>=3.16.2 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (4.2.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (7.35.1)
Requirement already satisfied: websockets>=13.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from yfinance) (16.1.1)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.1)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.4.22)
Requirement already satisfied: rich in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: pycparser in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from requests>=2.31->yfinance) (3.14)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from requests>=2.31->yfinance) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\rahul\PycharmProjects\learning_curve\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import numpy as np
import pandas as pd
import yfinance as yf
import  matplotlib.pyplot as plt

In [9]:
#Define the stock to analyze
stocks = ['AAPL','GOOGL','AMZN']

#Define the time period (Last 2 years )

start_date = '2024-01-01'
end_date = '2025-01-01'


#Dowmload data for the each stock
stock_date = yf.download(stocks, start_date, end_date)

[*********************100%***********************]  3 of 3 completed

In [10]:
#Fetch the top 5

stock_date.head()

Price            Close                                High              \
Ticker            AAPL        AMZN       GOOGL        AAPL        AMZN
Date
2024-01-02  183.562180  149.929993  136.955582  186.330843  152.380005
2024-01-03  182.187744  148.470001  137.698990  183.799505  151.050003
2024-01-04  179.873947  144.570007  135.191223  181.040733  147.380005
2024-01-05  179.152130  145.240005  134.537033  180.714448  146.589996
2024-01-08  183.483093  149.100006  137.619690  183.522654  149.399994

Price                          Low                                Open  \
Ticker           GOOGL        AAPL        AMZN       GOOGL        AAPL
Date
2024-01-02  138.224330  181.831767  148.389999  135.280433  185.055273
2024-01-03  138.402756  181.376915  148.330002  135.875166  182.158081
2024-01-04  137.936881  178.855477  144.050003  135.151581  180.111251
2024-01-05  135.954472  178.153440  144.529999  133.962129  179.953077
2024-01-08  137.788194  179.468538  146.149994  135.062365  180.051930

Price                                 Volume
Ticker            AMZN       GOOGL      AAPL      AMZN     GOOGL
Date
2024-01-02  151.539993  137.332247  82488700  47339400  23711200
2024-01-03  149.199997  136.043670  58414500  49425500  24212100
2024-01-04  145.589996  137.203380  71983600  56039800  27137700
2024-01-05  144.690002  135.548072  62379700  45153100  22513900
2024-01-08  146.740005  135.092100  59144500  46757100  21404000

In [11]:
#Finally save the data to CSV file for the future analysis

stock_date.to_csv('stock_date.csv')

# Data Manipulation

In [49]:
df =pd.read_csv(r'C:\Users\rahul\PycharmProjects\learning_curve\Project\stock_date.csv')

df.head()

,Price,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-02,183.5621795654297,149.92999267578125,136.95558166503906,186.33084291740326,152.3800048828125,138.2243301608941,181.83176685644636,148.38999938964844,135.28043314911363,185.0552730997862,151.5399932861328,137.3322465738531,82488700,47339400,23711200
3,2024-01-03,182.187744140625,148.47000122070312,137.69898986816406,183.79950485996184,151.0500030517578,138.4027561263541,181.37691491631995,148.3300018310547,135.87516579367383,182.15808112880916,149.1999969482422,136.04366979922918,58414500,49425500,24212100
4,2024-01-04,179.8739471435547,144.57000732421875,135.19122314453125,181.04073256447913,147.3800048828125,137.93688094484938,178.85547678867908,144.0500030517578,135.15158137245075,180.1112512492328,145.58999633789062,137.20337960162615,71983600,56039800,27137700

In [24]:
#Data cleaning  --> outlier,Null,Nan
#print(df.isnull())  #Return the Boolean values

str_cols = df.select_dtypes(include=['object', 'string']).columns
df[str_cols] = df[str_cols].fillna("0")


print(df.head())

        Price              Close             Close.1             Close.2  \
0      Ticker               AAPL                AMZN               GOOGL
1        Date                  0                   0                   0
2  2024-01-02  183.5621795654297  149.92999267578125  136.95558166503906
3  2024-01-03   182.187744140625  148.47000122070312  137.69898986816406
4  2024-01-04  179.8739471435547  144.57000732421875  135.19122314453125

                 High             High.1              High.2  \
0                AAPL               AMZN               GOOGL
1                   0                  0                   0
2  186.33084291740326  152.3800048828125   138.2243301608941
3  183.79950485996184  151.0500030517578   138.4027561263541
4  181.04073256447913  147.3800048828125  137.93688094484938

                  Low               Low.1               Low.2  \
0                AAPL                AMZN               GOOGL
1                   0                   0                   0
2  181.83176685644636  148.38999938964844  135.28043314911363
3  181.37691491631995   148.3300018310547  135.87516579367383
4  178.85547678867908   144.0500030517578  135.15158137245075

                 Open              Open.1              Open.2    Volume  \
0                AAPL                AMZN               GOOGL      AAPL
1                   0                   0                   0         0
2   185.0552730997862   151.5399932861328   137.3322465738531  82488700
3  182.15808112880916   149.1999969482422  136.04366979922918  58414500
4   180.1112512492328  145.58999633789062  137.20337960162615  71983600

   Volume.1  Volume.2
0      AMZN     GOOGL
1         0         0
2  47339400  23711200
3  49425500  24212100
4  56039800  27137700

In [21]:
import pandas as pd
print(pd.__version__)

3.0.3

In [28]:
#Drop Nan

print(df.dropna(inplace=True))

df

None

,Price,Close,Close.1,Close.2,High,High.1,High.2,Low,Low.1,Low.2,Open,Open.1,Open.2,Volume,Volume.1,Volume.2
0,Ticker,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL,AAPL,AMZN,GOOGL
2,2024-01-02,183.5621795654297,149.92999267578125,136.95558166503906,186.33084291740326,152.3800048828125,138.2243301608941,181.83176685644636,148.38999938964844,135.28043314911363,185.0552730997862,151.5399932861328,137.3322465738531,82488700,47339400,23711200
3,2024-01-03,182.187744140625,148.47000122070312,137.69898986816406,183.79950485996184,151.0500030517578,138.4027561263541,181.37691491631995,148.3300018310547,135.87516579367383,182.15808112880916,149.1999969482422,136.04366979922918,58414500,49425500,24212100
4,2024-01-04,179.8739471435547,144.57000732421875,135.19122314453125,181.04073256447913,147.3800048828125,137.93688094484938,178.85547678867908,144.0500030517578,135.15158137245075,180.1112512492328,145.58999633789062,137.20337960162615,71983600,56039800,27137700
5,2024-01-05,179.15213012695312,145.24000549316406,134.5370330810547,180.7144477397177,146.58999633789062,135.9544723417591,178.15344001418788,144.52999877929688,133.96212902161366,179.953076851374,144.69000244140625,135.54807229763554,62379700,45153100,22513900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2024-12-24,256.560791015625,229.0500030517578,195.09100341796875,256.57070690893096,229.13999938964844,195.09100341796875,253.66924678278625,226.1300048828125,192.7731083908338,253.86798918256417,226.94000244140625,193.82759815006608,23234700,15007500,10403300
250,2024-12-26,257.3755798339844,227.0500030517578,194.5836639404297,258.44874034869076,228.5,195.7276824419866,255.99442012888886,226.6699981689453,193.37000187433253,256.55086249805703,228.5,194.1359900072514,27237100,16146700,12046600
251,2024-12-27,253.96737670898438,223.75,191.75839233398438,257.05764856283577,226.02999877929688,194.3051030426647,251.45343969164696,220.89999389648438,189.65935551931798,256.19314630806485,225.60000610351562,193.9370152813754,42355300,27367100,18891400
252,2024-12-30,250.59890747070312,221.3000030517578,190.24630737304688,251.890657464443,223.0,191.5494980812226,249.15811581542044,218.42999267578125,188.13731273783964,250.6287158030117,220.05999755859375,188.8137872976618,35557500,28321200,14264700
253,2024-12-31,248.83021545410156,219.38999938964844,188.31639099121094,251.6720594492945,223.22999572753906,190.96257314438756,247.84649497663966,218.94000244140625,187.53048736926948,250.83739579916153,222.97000122070312,190.08714080992223,39480700,24819700,17466900

# #Statistical analysis

In [54]:


print(df.columns)


print('--------------------------------------')
df1 = df[['Price','High']]

print("Fetch top 5 rows ")

df1.head()

Index(['Price', 'Close', 'Close.1', 'Close.2', 'High', 'High.1', 'High.2',
       'Low', 'Low.1', 'Low.2', 'Open', 'Open.1', 'Open.2', 'Volume',
       'Volume.1', 'Volume.2'],
      dtype='str')
--------------------------------------
Fetch top 5 rows

        Price                High
0      Ticker                AAPL
1        Date                 NaN
2  2024-01-02  186.33084291740326
3  2024-01-03  183.79950485996184
4  2024-01-04  181.04073256447913

In [57]:
#Running sum


# Convert 'High' to numeric, forcing errors to NaN
df1['High'] = pd.to_numeric(df1['High'], errors='coerce')

# Now apply cumulative sum
df1['AAPL_HIGH_Cumsum'] = df1['High'].cumsum()

print(df1.head())

        Price        High  AAPL_HIGH_Cumsum
0      Ticker         NaN               NaN
1        Date         NaN               NaN
2  2024-01-02  186.330843        186.330843
3  2024-01-03  183.799505        370.130348
4  2024-01-04  181.040733        551.171080